name: Build Cordova APK

on:
  workflow_dispatch:   # 👈 Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Cordova
      run: npm install -g cordova

    - name: Setup Java & Android SDK
      uses: android-actions/setup-android@v3

    - name: Build APK
      run: |
        cordova platform add android
        cordova plugin add cordova-plugin-file
        cordova plugin add cordova-plugin-file-transfer
        cordova plugin add cordova-plugin-advanced-http
        cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-APK
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
